version: "3.8"
services:
  frontend:
    hostname: client
    restart: always
    image: node:18-alpine
    container_name: feed_app_frontend
    command: sh -c "cd /app && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  db:
    container_name: feed_app_db
    hostname: db
    restart: always
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rootPasssword
      - POSTGRES_DB=asapfeed
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432

  backend:
    hostname: server
    restart: always
    image: node:18-alpine
    container_name: feed_app_backend
    command: sh -c "cd /app && yarn start:dev"
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    environment:
      - PORT=3001
      - NODE_ENV=development
    depends_on:
      - db
